feat: added 'about', 'author'
ZZohanDvir/testguru pull request #1
Opened 2023-03-25 20:23 UTC by ZZohanDvir

Lesson 1 homework

2023-03-26 10:00 UTC, VidgarVii requested changes

2023-03-26 10:00 UTC, VidgarVii commented on README.md
> +    Student
Не много странный выбор пользователей системы. Ни каких учителей и студентов не будет

2023-03-26 10:00 UTC, VidgarVii commented on README.md
> +    Answer
не хватает сущности куда будем писать результат прохождения теста.
Так же в скринкастах и прошлых ТЗ говорилось про Категории

2023-03-26 10:00 UTC, VidgarVii commented on bin/webpack-dev-server
> +end
файлы выше не относятся к ТЗ. Они должны быть уже в мастер ветке

2023-03-26 10:00 UTC, VidgarVii commented on config/application.rb
> +    config.i18n.load_path += Dir[Rails.root.join('my', 'locales', '*.{rb,yml}')]
что означает эта настройка? Как она решает проблему локали по умолчанию?

2023-03-26 10:00 UTC, VidgarVii commented on config/application.rb
> +    config.i18n.default_locale = :ru
чтобы не было ошибок в системе, надо еще добавить файл конфигураций в папку config/locales ru.yml. Содержание почти аналогичное как en.yml

2023-03-26 10:00 UTC, VidgarVii commented on public/about.html
> +    <p>Также TestGuru является учебным проектом в рамках курса Ruby on Rails <a href="www.thinknetica.com">онлайн-школы Thinknetica</a></p>
ссылки на сторонние ресурсы правильно открывать в новой вкладке и хорошо бы добавить опцию rel=nofollow rel=noopener. Так клиента сохраним и поискового робота дальше не пустим

2023-03-26 10:00 UTC, VidgarVii commented on public/author.html
> +</html>
в конце файла надо отставлять 1 пустую строчку. Это указатель на конец файла. Сейчас система думает, что происходит обрыв файла. Даже гитхаб ругается. No new lina at end of file. Многие компиляторы тут выдадут ошибку. Руби частично компилируемый язык. И такой разрыв легко проглотит. Но в реальных проектах это как красная тряпка для быка. Так что тренируем дисциплину и больше такого не совершаем! В руби за чистоту кода!

2023-03-26 10:00 UTC, VidgarVii commented on public/author.html
> +<!DOCTYPE html>
эта страница должна быть доступна по пути `/about/author`, а сейчас доступна по`/author`
ТЗ: "Добавьте статическую страницу /about/author с информацией об авторе (включая ссылку на GitHub профиль)"

2023-03-29 04:55 UTC, VidgarVii requested changes

2023-03-29 04:55 UTC, VidgarVii commented on config/initializers/locale.rb
> +I18n.load_path += Dir[Rails.root.join('lib', 'locale', '*.{rb,yml}')]
я уже задавал вопрос об этой настройке https://github.com/ZZohanDvir/testguru/pull/1#discussion_r1148519757
Не разобравшись как что работает не стоит в слепую копировать чужой код и вставлять сюда

2023-03-29 04:55 UTC, VidgarVii commented on config/initializers/locale.rb
> +I18n.available_locales = [:en, :ru]
об этом не говорилось в ТЗ

2023-03-29 04:55 UTC, VidgarVii commented on config/initializers/locale.rb
> +I18n.default_locale = :ru
базовые вещи конфигурируется в файле config/application.rb
Об этом же говориться в документации rusrails

2023-03-29 04:55 UTC, VidgarVii commented on config/locales/ru.yml
> +
в конце файла надо отставлять 1 пустую строчку. Это указатель на конец файла. Сейчас система думает, что происходит обрыв файла. Даже гитхаб ругается. No new lina at end of file. Многие компиляторы тут выдадут ошибку. Руби частично компилируемый язык. И такой разрыв легко проглотит. Но в реальных проектах это как красная тряпка для быка. Так что тренируем дисциплину и больше такого не совершаем! В руби за чистоту кода!

2023-03-29 04:55 UTC, VidgarVii commented on public/about.html
>        <li>Создание тестов и управление ими</li>
нельзя мержить код в мастер если ПР и ТЗ не был принят. Иначе в ПР не попадёт весь нужный код. И придётся удалять лишний код из мастер ветки и переделывать задание.

2023-03-29 16:38 UTC, VidgarVii requested changes

2023-03-29 16:38 UTC, VidgarVii commented on config/application.rb
> +    I18n.default_locale = :ru
сильно выбивается из стиля.
Тут задаются базовые настройки приложения исползуется объект config
В документации, которой я скидывал до этого есть примеры http://rusrails.ru/i18n#konfigurirovanie-modulya-i18n

2023-03-29 16:38 UTC, VidgarVii commented on bin/webpack-dev-server
> +end
не исправлено

2023-03-29 16:38 UTC, VidgarVii commented on config/application.rb
> +    I18n.available_locales = [:en, :ru]
https://github.com/ZZohanDvir/testguru/pull/1#discussion_r1151391178
не исправлено

2023-03-29 17:08 UTC, ZZohanDvir commented on bin/webpack-dev-server
> +end
По поводу Webpack. Еще до начала проекта у меня были установлены Rails7. Для создания проекта пришлось востользоваться gemset'ом. Отсутствие webpack'а заметил только когда попытался запустить сервер.

2023-03-30 05:33 UTC, VidgarVii requested changes

2023-03-30 05:33 UTC, VidgarVii commented on bin/webpack-dev-server
> +end
файлы не убраны в мастер. В ТЗ не сказано, чтобы файлы вебпака были в ПР. ПР должен показывать код только относящийся к текущему заданию.

2023-03-30 05:33 UTC, VidgarVii commented on config/application.rb
> +    config.I18n.available_locales = [:en, :ru]
не исправлено

2023-03-30 05:33 UTC, VidgarVii commented on config/application.rb
> +    config.I18n.default_locale = :ru
нет такого конфига config.I18n
Будь внимательней и стоит уже прочитать документацию

2023-04-26 18:14 UTC, merged