fetech: add models and some migrations
ZZohanDvir/testguru pull request #3
Opened 2023-04-27 16:57 UTC by ZZohanDvir

2023-04-27 18:59 UTC, VidgarVii requested changes

2023-04-27 18:59 UTC, VidgarVii commented on app/models/answer.rb
> +  belongs_to :question
ассоциации позже будут в курсе
пока лучше убери их из моделей, чтобы они не отвлекали. Тем более они объявлены не верно.
Нам на данном этапе внешних ключей в таблицах вполне достаточно ближайшие пару уроков нужно будет ручками конструировать запросы, чтобы лучше понять, как ассоциации работают, а потом уже будем использовать ассоциации

2023-04-27 18:59 UTC, VidgarVii commented on db/migrate/20230427164159_create_answers.rb
> +      t.boolean :correct, default: false
для логических полей рекомендуется указывать опцию `null: false`
тогда в базе будут возможны строго два значения `true` или `false` вместо трех (`null/true/false`)

2023-04-27 18:59 UTC, VidgarVii commented on db/migrate/20230427164317_create_users.rb
> +      t.integer :role
скажу сразу это поле не будет использоваться.

2023-04-27 18:59 UTC, VidgarVii commented on db/migrate/20230427164424_create_tests.rb
> +      t.integer :level, default: 0
null: false

2023-04-27 18:59 UTC, VidgarVii commented on db/migrate/20230427164424_create_tests.rb
> +
для теста нам еще понадобиться автор. Это юзер который создал тест. Но при этом по названию колонки должно быть понятно, что речь идёт именно об авторе теста. Предлагаю это сделать в текущем ПР.

2023-04-29 17:00 UTC, BubuntuClu commented on db/migrate/20230427164424_create_tests.rb
> +      t.references :user, column: :author, null: false, foreign_key: true
если ты посмотришь на файл `schema.rb` то ты увидишь что этой колонки нет в таблице. что-то пошло не так при создании этой колонки.

и в `schema.rb` есть поле `role` у таблицы пользователей, но при этом в миграции уже нет этого поля. 
ты не забыл ли случайно файл добавить в коммит?

2023-04-30 05:59 UTC, ZZohanDvir commented on db/migrate/20230427164424_create_tests.rb
> +      t.references :user, column: :author, null: false, foreign_key: true
Забыл откатить миграции и накатить заново после корректировки.

2023-05-05 16:12 UTC, merged